import type {} from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Promotion } from '@/components/Promotion'
import { ProductData } from 'types/Product'
import { getProducts } from '@/lib/api'
import { ReactElement } from 'react'
interface Props {
  data: ProductData[]
}

const Home = ({ data }: Props) => {
  return (
    <div className="container mx-auto">
      <Head>
        <title>Product</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <Promotion />
        <div className="bg-white">
          <div className="mx-auto max-w-2xl py-16 px-4 sm:py-24 sm:px-6 lg:max-w-7xl lg:px-8">
            <h2 className="text-2xl font-extrabold tracking-tight text-gray-900">Customers also purchased</h2>

            <div className="mt-6 grid grid-cols-1 gap-y-10 gap-x-6 sm:grid-cols-2 lg:grid-cols-4 xl:gap-x-8">
              {data.map((product: ProductData) => (
                <div key={product.id} className="group relative">
                  {product.attributes.images.data.length > 0 && (
                    <div className="min-h-80 aspect-w-1 aspect-h-1 w-full overflow-hidden rounded-md bg-gray-200 group-hover:opacity-75 lg:h-80">
                      <Image
                        src={`http://localhost:1337${product.attributes.images.data[0].attributes.url}`}
                        alt={product.attributes.title}
                        className="h-full w-full object-cover object-center lg:h-full lg:w-full"
                        layout={'fill'}
                      />
                    </div>
                  )}
                  <div className="mt-4 flex justify-between">
                    <div>
                      <h3 className="text-sm text-gray-700">
                        <Link href={`/products/${product.id}`} passHref>
                          <a>
                            <span aria-hidden="true" className="absolute inset-0" />

                            {product.attributes.title}
                          </a>
                        </Link>
                      </h3>
                      <p className="mt-2 text-sm text-gray-500">{product.attributes.description}</p>
                    </div>
                    <p className="ml-2 text-sm font-medium text-gray-900">{product.attributes.price}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </main>

      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export const getStaticProps = async () => {
  const data = await getProducts()
  return {
    props: { data },
    revalidate: 10,
  }
}

Home.getLayout = function getLayout(page: ReactElement) {
  return page
}

export default Home
